version: "2"

services:
  web:
    image: golang:1.8.1-alpine
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/user_endpoint
    working_dir: /go/src/user_endpoint
    command: go run app/app.go

